CC = gcc
CFLAGS = -Wall -g -o

OBJS = parser.c main.c

all: wsh start

wsh: $(OBJS)
	$(CC) $(CFLAGS) $@ $(OBJS)
clean:
	rm -f *.o *~ *.txt core wsh
depend:
	makedepend main.c parser.c
start:
	echo "\n\n\n\nWELCOME TO THE WSHELL!!\nHERE WE HAVE AN EXPLANATION FOR THE BASIC COMMANDS IN A SHELL:\n\n\tcommand -> IT EXECS THE BASIC COMMAND\n\n\tcommand > file -> IT EXECS THE BASIC COMMAND WITH THE OUTPUT DIRECTED TO THE FILE\n\n\tcommand < file -> IT EXECS THE BASIC COMMAND WHERE THE INPUT IS DIRECTED FROM THE FILE\n\n\tcommand >& file -> IT EXECS THE BASIC COMMAND WITH THE ERROR OUTPUT DIRECTED TO THE FILE\n\n\tcommand | command -> IT EXECS THE FIRST COMMAND AND THE OUTPUT OF THAT IS USED AS THE INPUT FOR THE SECOND COMMAND\n\n\tcommand & -> IT EXECS THE COMMAND ON THE BACKGROUND, SO YOU CAN EXEC OTHER COMMANDS WHILE\n\n\tcommand ; command -> IT EXECS THE SECOND COMMAND RIGHT AFTER THE FIRST ONE, WHETHER THE FIRST COMMAND FAILED OR NOT\n\n\tPLEASE TYPE "./wsh" TO START THE WSHELL"
